apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: load-balancer
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: firas124578/api
          env:
            - name: REDIS_HOST
              value: redis-service
          ports:
            - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: load-balancer
spec:
  type: NodePort
  selector:
    app: api
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 31001
