apiVersion: apps/v1
kind: Deployment
metadata:
  name: rp
  namespace: load-balancer
spec:
  selector:
    matchLabels:
      app: rp
  template:
    metadata:
      labels:
        app: rp
    spec:
      containers:
        - name: rp
          image: firas124578/rp
          ports:
            - containerPort: 443
            - containerPort: 3333
              name: server-entry
          volumeMounts:
            - mountPath: /etc/nginx/conf.d/
              name: config-pvv
      volumes:
        - name: config-pvv
          persistentVolumeClaim:
            claimName: config-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: rp-service
  namespace: load-balancer
spec:
  type: NodePort
  selector:
    app: rp
  ports:
    - port: 443
      targetPort: 443
      nodePort: 31000

---
apiVersion: v1
kind: Service
metadata:
  name: server-service
  namespace: load-balancer
spec:
  selector:
    app: rp
  ports:
    - port: 3333
      targetPort: 3333
